const $=s=>document.querySelector(s);
const ui={source:$('#sourceText'),lang:$('#languageSelect'),analyze:$('#analyzeBtn'),demo:$('#demoBtn'),clear:$('#clearBtn'),file:$('#fileInput'),preview:$('#sentencePreview'),status:$('#statusPill'),metrics:$('#metricGrid'),report:$('#report'),actions:$('#reportActions'),copy:$('#copyBtn'),download:$('#downloadBtn')};

const T={
 de:{language:'Sprache',privacy:'Datenschutz',apk:'APK laden',heroTitle:'Jeden Satz sehen. Unschärfen sichtbar machen.',heroText:'Volltext-Audit für Variablenbindung, Ghost-Context, destruktive und konstruktive Rahmung, Verantwortungsdiffusion und Zielgruppen-Resonanz.',languages:'Sprachen',fullText:'Volltext-Parsing',processing:'Verarbeitung',source:'Quelltext',placeholder:'Gesamten Text hier einfügen …',file:'Datei öffnen',demo:'Demo',clear:'Leeren',analyze:'Vollständig analysieren',localNote:'Analyse läuft lokal im Browser. Bei HTML-Dateien wird sichtbarer Text extrahiert.',audit:'Audit',ready:'Bereit',empty:'Nach der Analyse erscheinen hier Volltext-Metriken.',copy:'Protokoll kopieren',download:'Markdown laden',method:'Methodik & Grenzen',method1:'<b>D-Faktor:</b> heuristische Schätzung der anaphorischen Distanz. D-0 gilt als lokal gebunden, D-1 als Vorgängersatz-Bezug, D-2+ als erhöhtes Ghost-Context-Risiko.',method2:'<b>Golem/Pygmalion:</b> rhetorische Framing-Tags. Sie sind keine Diagnose und kein Beweis einer neuronalen oder unbewussten „Programmierung“.',method3:'<b>Vollständigkeit:</b> Jeder erkannte Satz fließt in die Statistik ein. Die Detailsektion listet alle nicht-neutralen Sätze und konstruktiv bewerteten Sätze.',sentences:'Sätze',done:'Analysiert'},
 en:{language:'Language',privacy:'Privacy',apk:'Download APK',heroTitle:'See every sentence. Expose structural ambiguity.',heroText:'Full-text audit for variable binding, ghost context, destructive and constructive framing, responsibility diffusion and target-group resonance.',languages:'Languages',fullText:'Full-text parsing',processing:'Processing',source:'Source text',placeholder:'Paste the complete text here …',file:'Open file',demo:'Demo',clear:'Clear',analyze:'Analyze complete text',localNote:'Analysis runs locally in your browser. Visible text is extracted from HTML files.',audit:'Audit',ready:'Ready',empty:'Full-text metrics appear here after analysis.',copy:'Copy protocol',download:'Download Markdown',method:'Method & limits',method1:'<b>D-factor:</b> heuristic estimate of anaphoric distance. D-0 is locally bound, D-1 points to the previous sentence, D-2+ indicates increased ghost-context risk.',method2:'<b>Golem/Pygmalion:</b> rhetorical framing tags. They are not a diagnosis or proof of neural or subconscious “programming”.',method3:'<b>Completeness:</b> Every detected sentence enters the statistics. The detail section lists every non-neutral and constructive sentence.',sentences:'sentences',done:'Analyzed'},
 fr:{language:'Langue',privacy:'Confidentialité',apk:'Télécharger APK',heroTitle:'Voir chaque phrase. Révéler les ambiguïtés.',heroText:'Audit intégral de la liaison des variables, du ghost-context, du cadrage destructif/constructif, de la diffusion de responsabilité et de la résonance des publics.',languages:'Langues',fullText:'Analyse intégrale',processing:'Traitement',source:'Texte source',placeholder:'Collez ici le texte complet …',file:'Ouvrir un fichier',demo:'Démo',clear:'Effacer',analyze:'Analyser tout le texte',localNote:'L’analyse s’exécute localement dans le navigateur. Le texte visible est extrait des fichiers HTML.',audit:'Audit',ready:'Prêt',empty:'Les métriques apparaîtront ici après analyse.',copy:'Copier le protocole',download:'Télécharger Markdown',method:'Méthode & limites',method1:'<b>Facteur D :</b> estimation heuristique de la distance anaphorique. D-0 = liaison locale, D-1 = phrase précédente, D-2+ = risque accru de ghost-context.',method2:'<b>Golem/Pygmalion :</b> étiquettes de cadrage rhétorique, pas un diagnostic ni une preuve de « programmation » neuronale ou inconsciente.',method3:'<b>Exhaustivité :</b> chaque phrase détectée entre dans les statistiques. La section détaillée liste les phrases non neutres et constructives.',sentences:'phrases',done:'Analysé'},
 es:{language:'Idioma',privacy:'Privacidad',apk:'Descargar APK',heroTitle:'Ver cada frase. Hacer visible la ambigüedad.',heroText:'Auditoría de texto completo para enlace de variables, ghost-context, encuadre destructivo/constructivo, difusión de responsabilidad y resonancia de grupos.',languages:'Idiomas',fullText:'Texto completo',processing:'Procesamiento',source:'Texto fuente',placeholder:'Pega aquí el texto completo …',file:'Abrir archivo',demo:'Demo',clear:'Borrar',analyze:'Analizar texto completo',localNote:'El análisis se ejecuta localmente en el navegador. En HTML se extrae el texto visible.',audit:'Auditoría',ready:'Listo',empty:'Las métricas aparecerán aquí después del análisis.',copy:'Copiar protocolo',download:'Descargar Markdown',method:'Método y límites',method1:'<b>Factor D:</b> estimación heurística de distancia anafórica. D-0 = enlace local, D-1 = frase anterior, D-2+ = mayor riesgo de ghost-context.',method2:'<b>Golem/Pygmalion:</b> etiquetas retóricas de encuadre; no son diagnóstico ni prueba de “programación” neuronal o inconsciente.',method3:'<b>Integridad:</b> cada frase detectada entra en las estadísticas. La sección detallada lista frases no neutrales y constructivas.',sentences:'frases',done:'Analizado'},
 it:{language:'Lingua',privacy:'Privacy',apk:'Scarica APK',heroTitle:'Vedere ogni frase. Rendere visibili le ambiguità.',heroText:'Audit dell’intero testo per legame delle variabili, ghost-context, framing distruttivo/costruttivo, diffusione di responsabilità e risonanza dei gruppi.',languages:'Lingue',fullText:'Testo completo',processing:'Elaborazione',source:'Testo sorgente',placeholder:'Incolla qui il testo completo …',file:'Apri file',demo:'Demo',clear:'Cancella',analyze:'Analizza testo completo',localNote:'L’analisi avviene localmente nel browser. Nei file HTML viene estratto il testo visibile.',audit:'Audit',ready:'Pronto',empty:'Le metriche appariranno qui dopo l’analisi.',copy:'Copia protocollo',download:'Scarica Markdown',method:'Metodo e limiti',method1:'<b>Fattore D:</b> stima euristica della distanza anaforica. D-0 = legame locale, D-1 = frase precedente, D-2+ = maggiore rischio di ghost-context.',method2:'<b>Golem/Pygmalion:</b> etichette retoriche di framing; non sono diagnosi né prova di “programmazione” neurale o inconscia.',method3:'<b>Completezza:</b> ogni frase rilevata entra nelle statistiche. La sezione dettagliata elenca frasi non neutrali e costruttive.',sentences:'frasi',done:'Analizzato'},
 nl:{language:'Taal',privacy:'Privacy',apk:'APK downloaden',heroTitle:'Zie elke zin. Maak vaagheid zichtbaar.',heroText:'Volledige tekstaudit voor variabele binding, ghost-context, destructieve/constructieve framing, verantwoordelijkheidsdiffusie en doelgroepresonantie.',languages:'Talen',fullText:'Volledige tekst',processing:'Verwerking',source:'Brontekst',placeholder:'Plak hier de volledige tekst …',file:'Bestand openen',demo:'Demo',clear:'Wissen',analyze:'Volledige tekst analyseren',localNote:'Analyse draait lokaal in de browser. Bij HTML-bestanden wordt zichtbare tekst geëxtraheerd.',audit:'Audit',ready:'Gereed',empty:'Na analyse verschijnen hier de volledige tekstmetriek.',copy:'Protocol kopiëren',download:'Markdown downloaden',method:'Methode & grenzen',method1:'<b>D-factor:</b> heuristische schatting van anaforische afstand. D-0 = lokaal gebonden, D-1 = vorige zin, D-2+ = verhoogd ghost-context-risico.',method2:'<b>Golem/Pygmalion:</b> retorische framinglabels; geen diagnose of bewijs van neurale/onbewuste “programmering”.',method3:'<b>Volledigheid:</b> elke gedetecteerde zin telt mee. De detailsectie toont alle niet-neutrale en constructieve zinnen.',sentences:'zinnen',done:'Geanalyseerd'}
};

const LEX={
 de:{neg:['scheiter','missling','unmöglich','ohnmacht','machtlos','fehler','problem','krise','bedroh','gefähr','sabot','blockier','versag','kann nicht','nie ','niemals','verlust','zerstör'],pos:['erfolg','geling','lösung','lösbar','klar','präzis','machbar','möglich','verbesser','stärk','erreich','bewältig','sicherstell','klären','fortschritt'],pron:['er','sie','es','ihn','ihm','ihr','ihnen','dies','diese','dieser','das','deren','dessen'],diff:['man'],over:['wir','uns','unser']},
 en:{neg:['fail','failure','impossible','powerless','error','problem','crisis','threat','danger','sabot','block','cannot','can\'t','never','loss','destroy'],pos:['success','succeed','solution','solvable','clear','precise','feasible','possible','improve','strength','achiev','resolve','ensure','progress'],pron:['he','she','it','him','her','they','them','this','that','these','those','their'],diff:['one','people'],over:['we','us','our']},
 fr:{neg:['échou','échec','impossible','impuiss','erreur','problème','crise','menace','danger','sabot','bloqu','ne peut pas','jamais','perte','détru'],pos:['succès','réuss','solution','résol','clair','précis','faisable','possible','amélior','renfor','atteign','assur','progrès'],pron:['il','elle','ils','elles','lui','leur','ceci','cela','ce','cette','ces'],diff:['on'],over:['nous','notre','nos']},
 es:{neg:['fracas','fall','imposible','impotenc','error','problema','crisis','amenaza','pelig','sabot','bloque','no puede','nunca','pérdida','destru'],pos:['éxito','logr','solución','resolv','claro','precis','viable','posible','mejor','fortal','alcanz','asegur','progreso'],pron:['él','ella','ellos','ellas','lo','la','esto','eso','este','esta','estos','estas','su'],diff:['uno','se'],over:['nosotros','nosotras','nuestro','nuestra']},
 it:{neg:['falli','insuccess','impossibile','impotenz','errore','problema','crisi','minaccia','pericol','sabot','blocc','non può','mai','perdita','distru'],pos:['successo','riusc','soluzione','risolv','chiaro','precis','fattibile','possibile','miglior','rafforz','raggiung','assicura','progresso'],pron:['lui','lei','esso','essa','loro','questo','quello','questa','quella','suo','sua'],diff:['si'],over:['noi','nostro','nostra']},
 nl:{neg:['misluk','falen','onmogelijk','machteloos','fout','probleem','crisis','dreig','gevaar','sabot','blokkeer','kan niet','nooit','verlies','vernietig'],pos:['succes','slaag','oploss','duidelijk','precies','haalbaar','mogelijk','verbeter','versterk','bereik','verzeker','vooruitgang'],pron:['hij','zij','het','hem','haar','hen','dit','dat','deze','die','hun'],diff:['men'],over:['wij','we','ons','onze']}
};

const RL={
 de:{title:'# SEMANTISCHES FORENSIK- & AUDIT-PROTOKOLL',stats:'## 1. UMFASSENDE STATISTIK & METRIKEN',total:'Gesamtanzahl analysierter Sätze',bad:'Anteil SCHLECHTER Formulierungen',amb:'Anteil AMBIVALENTER Formulierungen',good:'Anteil GUTER Formulierungen',neutral:'Anteil NEUTRALER Formulierungen',specific:'**Spezifische Verteilungen:**',df:'D-Faktor (Ghost-Context-Risiko)',dom:'Dominierendes psychologisches Muster',danger:'Kritische / Hohe Gefährdungen absolut',details:'## 2. DETAILLIERTE ANALYSE DER ANOMALIEN & WIRKUNGSWEISEN',rating:'Wertung',risk:'Gefahr',quote:'Zitat',impact:'Pamphletische Gesamtwirkung',cat:'Kategorie & Struktur',res:'Zielgruppen-Resonanz',goodfor:'Gut für',badfor:'Schlecht für',mechanism:'Fehler-Beschreibung / Wirkungsweise',fix:'Korrektur-Vorschlag',critical:'KRITISCH',high:'HOCH',medium:'MITTEL',constructive:'Förderlich: Die Formulierung stärkt Klarheit, Lösungsorientierung oder Handlungsfähigkeit.',destructive:'Schädigend: Die Formulierung normalisiert negative Erwartungen, Unschärfe oder Handlungsblockaden.',mixed:'Ambivalent: konstruktive und destruktive Signale konkurrieren im selben Satz.',neutralImpact:'Neutral: überwiegend deskriptiv, ohne starkes Framing-Signal.',ghost:'Ghost-Context',golem:'Golem-Framing',pyg:'Pygmalion-Framing',diff:'Verantwortungsdiffusion',over:'Überinklusive Wir-Rahmung',precise:'Präzise Syntax',gfGhost:'Akteure, die von Interpretationsspielraum oder unklarer Verantwortlichkeit profitieren.',bfGhost:'Leser, Entscheider und Ausführende, die eindeutige Referenzen benötigen.',gfBad:'Kritiker, Konkurrenten oder Akteure, deren Position durch Passivität oder Scheitern gestärkt würde.',bfBad:'Adressaten, Projektverantwortliche und Teams, deren Handlungsfähigkeit durch negative Normalisierung sinken kann.',gfGood:'Adressaten, Macher und Teams, die von klaren nächsten Schritten und erreichbaren Zielen profitieren.',bfGood:'Akteure, die von Unklarheit, Blockade oder Resignation profitieren würden.',mechGhost:'Ein Bezugsausdruck ist heuristisch nicht lokal gebunden. Dadurch steigt der Interpretationsraum; Subjekt, Objekt oder Verantwortung können semantisch „wandern“.',mechBad:'Negative Erwartungsbegriffe werden ohne ebenso konkrete Lösungsbindung dominant. Das kann Scheitern oder Ohnmacht als Default-Rahmen setzen.',mechMixed:'Der Satz enthält zugleich fördernde und hemmende Rahmungen. Die Handlungsbotschaft bleibt dadurch psychologisch und semantisch geteilt.',mechGood:'Konstruktive Begriffe sind an Klarheit, Lösbarkeit oder konkrete Handlungsfähigkeit gekoppelt.',fixText:'Explizites Subjekt + konkrete Bedingung + lösbarer nächster Schritt formulieren; Pronomen eindeutig binden und negative Erwartung nicht als Normalzustand setzen.'},
 en:{title:'# SEMANTIC FORENSICS & AUDIT PROTOCOL',stats:'## 1. COMPREHENSIVE STATISTICS & METRICS',total:'Total sentences analyzed',bad:'Share of BAD formulations',amb:'Share of AMBIVALENT formulations',good:'Share of GOOD formulations',neutral:'Share of NEUTRAL formulations',specific:'**Specific distributions:**',df:'D-factor (ghost-context risk)',dom:'Dominant psychological pattern',danger:'Critical / high risks absolute',details:'## 2. DETAILED ANALYSIS OF ANOMALIES & EFFECTS',rating:'Rating',risk:'Risk',quote:'Quote',impact:'Overall pamphletic effect',cat:'Category & structure',res:'Target-group resonance',goodfor:'Good for',badfor:'Bad for',mechanism:'Error description / mechanism',fix:'Correction proposal',critical:'CRITICAL',high:'HIGH',medium:'MEDIUM',constructive:'Constructive: the wording supports clarity, solution orientation or agency.',destructive:'Harmful: the wording normalizes negative expectations, ambiguity or blocked action.',mixed:'Ambivalent: constructive and destructive signals compete in the same sentence.',neutralImpact:'Neutral: mainly descriptive, without strong framing.',ghost:'Ghost-context',golem:'Golem framing',pyg:'Pygmalion framing',diff:'Responsibility diffusion',over:'Over-inclusive “we” framing',precise:'Precise syntax',gfGhost:'Actors who benefit from interpretive latitude or unclear responsibility.',bfGhost:'Readers, decision-makers and implementers who require explicit references.',gfBad:'Critics, competitors or actors whose position benefits from passivity or failure.',bfBad:'Addressees, project owners and teams whose agency can be reduced by negative normalization.',gfGood:'Addressees, builders and teams who benefit from clear next steps and achievable goals.',bfGood:'Actors who would benefit from ambiguity, blockage or resignation.',mechGhost:'A reference expression is not heuristically bound locally. This widens interpretive space and can let subject, object or responsibility drift.',mechBad:'Negative expectation terms dominate without equally concrete solution binding, framing failure or powerlessness as a default.',mechMixed:'The sentence contains both enabling and inhibiting framing, leaving the action message semantically divided.',mechGood:'Constructive terms are tied to clarity, solvability or concrete agency.',fixText:'State an explicit subject, concrete condition and solvable next step; bind pronouns clearly and avoid presenting a negative expectation as the default state.'}
};
['fr','es','it','nl'].forEach(k=>RL[k]=RL.en);

function escapeRe(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function hasTerm(text,term){if(term.includes(' ')) return text.includes(term);return new RegExp(`(^|[^\\p{L}])${escapeRe(term)}`,'iu').test(text)}
function splitSentences(text){return (text.replace(/\r/g,'').match(/[^.!?…\n]+(?:[.!?…]+|(?=\n)|$)/g)||[]).map(s=>s.trim()).filter(Boolean)}
function pct(n,total){return total?((n/total)*100).toFixed(1):'0.0'}
function countTerms(lower,arr){return arr.reduce((n,t)=>n+(hasTerm(lower,t)?1:0),0)}
function pronounInfo(sentence,lang,index){const l=LEX[lang]||LEX.en, lower=sentence.toLocaleLowerCase(lang);const matches=l.pron.filter(p=>hasTerm(lower,p));if(!matches.length)return {d:'D-0',has:false};const firstWord=(lower.match(/[\p{L}’'-]+/u)||[''])[0];const starts=matches.includes(firstWord);const words=sentence.match(/[\p{L}À-ž][\p{L}À-ž’'-]*/gu)||[];const beforePron=words.findIndex(w=>matches.includes(w.toLocaleLowerCase(lang)));const explicitBefore=beforePron>0&&beforePron>=2;if(explicitBefore)return {d:'D-0',has:true};if(starts&&index>0)return {d:'D-1',has:true};return {d:index>0?'D-1':'D-2+',has:true}}
function classifySentence(sentence,lang,index){const l=LEX[lang]||LEX.en,lower=sentence.toLocaleLowerCase(lang);const neg=countTerms(lower,l.neg),pos=countTerms(lower,l.pos),diff=countTerms(lower,l.diff),over=countTerms(lower,l.over);const pi=pronounInfo(sentence,lang,index);let rating='NEUTRAL';if(pi.d==='D-2+'||neg>=2||neg>pos+1)rating='SCHLECHT';else if((neg>0&&pos>0)||diff>0||over>0||neg===1)rating='AMBIVALENT';else if(pos>0&&pi.d!=='D-2+')rating='GUT';let risk='-';if(pi.d==='D-2+'||neg>=2)risk='KRITISCH';else if(rating==='SCHLECHT'||(rating==='AMBIVALENT'&&neg>0))risk='HOCH';else if(pi.d==='D-1'||diff>0||over>0)risk='MITTEL';const tags=[];if(pi.d==='D-2+')tags.push('ghost');else tags.push(pi.d);if(neg)tags.push('golem');if(pos)tags.push('pyg');if(diff)tags.push('diff');if(over)tags.push('over');if(!neg&&!pos&&pi.d==='D-0'&&!diff&&!over)tags.push('precise');return {sentence,index,neg,pos,diff,over,d:pi.d,rating,risk,tags}}
function dominant(results){const sums={Golem:0,Pygmalion:0,'Ghost-Context':0,'Verantwortungsdiffusion':0};results.forEach(r=>{sums.Golem+=r.neg;sums.Pygmalion+=r.pos;sums['Ghost-Context']+=r.d==='D-2+'?1:0;sums.Verantwortungsdiffusion+=r.diff+r.over});return Object.entries(sums).sort((a,b)=>b[1]-a[1])[0][1]===0?'Kein stark dominierendes Muster':Object.entries(sums).sort((a,b)=>b[1]-a[1])[0][0]}
function localizedTag(tag,r){if(tag==='D-0'||tag==='D-1')return tag;if(tag==='ghost')return `${r.ghost} (D-2+)`;if(tag==='golem')return r.golem;if(tag==='pyg')return r.pyg;if(tag==='diff')return r.diff;if(tag==='over')return r.over;return r.precise}
function detailNarrative(x,r){let impact=r.neutralImpact,goodfor=r.gfGood,badfor=r.bfGood,mechanism=r.mechGood;if(x.rating==='SCHLECHT'){impact=r.destructive;goodfor=x.d==='D-2+'?r.gfGhost:r.gfBad;badfor=x.d==='D-2+'?r.bfGhost:r.bfBad;mechanism=x.d==='D-2+'?r.mechGhost:r.mechBad}else if(x.rating==='AMBIVALENT'){impact=r.mixed;goodfor=x.d==='D-2+'?r.gfGhost:r.gfBad;badfor=x.d==='D-2+'?r.bfGhost:r.bfBad;mechanism=r.mechMixed}else if(x.rating==='GUT'){impact=r.constructive}return {impact,goodfor,badfor,mechanism}}
function buildReport(results,lang){const r=RL[lang]||RL.en,total=results.length,count=k=>results.filter(x=>x.rating===k).length,bad=count('SCHLECHT'),amb=count('AMBIVALENT'),good=count('GUT'),neutral=count('NEUTRAL');const d0=results.filter(x=>x.d==='D-0').length,d1=results.filter(x=>x.d==='D-1').length,d2=results.filter(x=>x.d==='D-2+').length,danger=results.filter(x=>x.risk==='KRITISCH'||x.risk==='HOCH').length;const lines=[r.title,'',r.stats,`*   **${r.total}:** ${total}`,`*   **${r.bad}:** ${pct(bad,total)}% (${bad} Sätze)`,`*   **${r.amb}:** ${pct(amb,total)}% (${amb} Sätze)`,`*   **${r.good}:** ${pct(good,total)}% (${good} Sätze)`,`*   **${r.neutral}:** ${pct(neutral,total)}% (${neutral} Sätze)`,'',r.specific,`*   **${r.df}:** D-0: ${pct(d0,total)}% | D-1: ${pct(d1,total)}% | D-2+: ${pct(d2,total)}%`,`*   **${r.dom}:** ${dominant(results)}`,`*   **${r.danger}:** ${danger}`,'','---','',r.details,''];const order={KRITISCH:0,HOCH:1,MITTEL:2,'-':3};const detailed=results.filter(x=>x.rating!=='NEUTRAL').sort((a,b)=>(order[a.risk]-order[b.risk])||(a.index-b.index));detailed.forEach((x,i)=>{const n=detailNarrative(x,r);const riskName=x.risk==='KRITISCH'?r.critical:x.risk==='HOCH'?r.high:x.risk==='MITTEL'?r.medium:'-';lines.push(`### ${i+1} | ${r.rating}: ${x.rating} | ${r.risk}: ${riskName}`,`*   **${r.quote}:** "${x.sentence.replace(/"/g,'“')}"`,`*   **${r.impact}:** ${n.impact}`,`*   **${r.cat}:** ${x.tags.map(t=>localizedTag(t,r)).join(' · ')}`,`*   **${r.res}:**`,`    *   *${r.goodfor}:* ${n.goodfor}`,`    *   *${r.badfor}:* ${n.badfor}`,`*   **${r.mechanism}:** ${n.mechanism}`);if(x.rating==='SCHLECHT'||x.rating==='AMBIVALENT')lines.push(`*   **${r.fix}:** ${r.fixText}`);lines.push('')});return {text:lines.join('\n'),counts:{bad,amb,good,neutral,d0,d1,d2,danger,total}}}

function run(){const text=ui.source.value.trim();const lang=ui.lang.value;if(!text){ui.source.focus();return}const sentences=splitSentences(text);const results=sentences.map((s,i)=>classifySentence(s,lang,i));const built=buildReport(results,lang);ui.report.textContent=built.text;renderMetrics(built.counts);ui.actions.classList.remove('hidden');ui.status.textContent=`${T[lang].done}: ${built.counts.total}`;ui.status.classList.add('active');window.__antiGolemReport=built.text;window.__antiGolemLastSource=text;localStorage.setItem('antigolem.lang',lang)}
function renderMetrics(c){const t=ui.lang.value==='de'?{bad:'SCHLECHT',amb:'AMBIVALENT',good:'GUT',neutral:'NEUTRAL',d:'D-2+ Risiko',total:'Sätze'}:{bad:'BAD',amb:'AMBIVALENT',good:'GOOD',neutral:'NEUTRAL',d:'D-2+ risk',total:'Sentences'};ui.metrics.className='metrics';ui.metrics.innerHTML=`<div class="metric bad"><span>${t.bad}</span><b>${pct(c.bad,c.total)}%</b></div><div class="metric amb"><span>${t.amb}</span><b>${pct(c.amb,c.total)}%</b></div><div class="metric good"><span>${t.good}</span><b>${pct(c.good,c.total)}%</b></div><div class="metric neutral"><span>${t.neutral}</span><b>${pct(c.neutral,c.total)}%</b></div><div class="metric"><span>${t.d}</span><b>${pct(c.d2,c.total)}%</b></div><div class="metric"><span>${t.total}</span><b>${c.total}</b></div>`}
function updatePreview(){const n=splitSentences(ui.source.value).length;ui.preview.textContent=`${n} ${T[ui.lang.value].sentences}`}
function applyLanguage(){const lang=ui.lang.value,dict=T[lang];document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(dict[k])el.innerHTML=dict[k]});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const k=el.dataset.i18nPlaceholder;if(dict[k])el.placeholder=dict[k]});localStorage.setItem('antigolem.lang',lang);updatePreview()}
function demoText(lang){const d={de:'Viele Projekte scheitern, weil man zu spät reagiert. Das führt oft zu Problemen. Ein präziser Prüfprozess schafft Klarheit und macht den nächsten Schritt lösbar. Wir müssen das jetzt einfach richtig machen.',en:'Many projects fail because people react too late. This often causes problems. A precise review process creates clarity and makes the next step solvable. We simply have to get this right now.',fr:'De nombreux projets échouent parce qu’on réagit trop tard. Cela crée souvent des problèmes. Un processus de contrôle précis apporte de la clarté et rend la prochaine étape résoluble.',es:'Muchos proyectos fracasan porque se reacciona demasiado tarde. Esto suele causar problemas. Un proceso de revisión preciso aporta claridad y hace resoluble el siguiente paso.',it:'Molti progetti falliscono perché si reagisce troppo tardi. Questo spesso crea problemi. Un processo di revisione preciso porta chiarezza e rende risolvibile il passo successivo.',nl:'Veel projecten mislukken omdat men te laat reageert. Dit veroorzaakt vaak problemen. Een precies beoordelingsproces schept duidelijkheid en maakt de volgende stap oplosbaar.'};return d[lang]||d.en}

ui.analyze.addEventListener('click',run);ui.source.addEventListener('input',updatePreview);ui.lang.addEventListener('change',()=>{applyLanguage();if(ui.report.textContent)run()});ui.demo.addEventListener('click',()=>{ui.source.value=demoText(ui.lang.value);updatePreview();run()});ui.clear.addEventListener('click',()=>{ui.source.value='';ui.report.textContent='';ui.metrics.className='metrics emptyState';ui.metrics.innerHTML=`<p>${T[ui.lang.value].empty}</p>`;ui.actions.classList.add('hidden');ui.status.textContent=T[ui.lang.value].ready;ui.status.classList.remove('active');updatePreview()});ui.copy.addEventListener('click',async()=>{if(window.__antiGolemReport)await navigator.clipboard.writeText(window.__antiGolemReport)});ui.download.addEventListener('click',()=>{if(!window.__antiGolemReport)return;const blob=new Blob([window.__antiGolemReport],{type:'text/markdown;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`antigolem-audit-${new Date().toISOString().slice(0,10)}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});ui.file.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;let text=await f.text();if(/\.html?$/i.test(f.name)){const doc=new DOMParser().parseFromString(text,'text/html');text=doc.body?.innerText||text}ui.source.value=text;updatePreview()});

const saved=localStorage.getItem('antigolem.lang');if(saved&&T[saved])ui.lang.value=saved;applyLanguage();

// Android bridge: AccessibilityService stores captured text, MainActivity injects it here.
window.AntiGolem={setCapturedText(text){ui.source.value=String(text||'');updatePreview();run()}};
