(() => {
  const L={de:{export:'Export',txt:'TXT',md:'Markdown',pdf:'PDF'},en:{export:'Export',txt:'TXT',md:'Markdown',pdf:'PDF'},fr:{export:'Exporter',txt:'TXT',md:'Markdown',pdf:'PDF'},es:{export:'Exportar',txt:'TXT',md:'Markdown',pdf:'PDF'},it:{export:'Esporta',txt:'TXT',md:'Markdown',pdf:'PDF'},nl:{export:'Exporteren',txt:'TXT',md:'Markdown',pdf:'PDF'}};
  const d=()=>L[ui.lang.value]||L.en;
  function download(content,type,name){const blob=new Blob([content],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
  function date(){return new Date().toISOString().slice(0,10)}
  async function loadJsPdf(){if(globalThis.jspdf?.jsPDF)return globalThis.jspdf.jsPDF;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)});return globalThis.jspdf.jsPDF;}
  async function pdf(){const text=ui.source.value;if(!text.trim())return;try{const JsPDF=await loadJsPdf(),doc=new JsPDF({unit:'pt',format:'a4'}),margin=48,width=595.28-96,height=841.89-96,lines=doc.splitTextToSize(text,width);let y=55;doc.setFont('helvetica','normal');doc.setFontSize(10.5);for(const line of lines){if(y>height+38){doc.addPage();y=55;}doc.text(line,margin,y);y+=14;}doc.save(`antigolem-text-${date()}.pdf`);}catch(e){console.error(e);alert('PDF export could not be initialized.');}}
  function mount(){const row=document.querySelector('.inputPanel .toolRow');if(!row||document.getElementById('agExportGroup'))return;const box=document.createElement('span');box.id='agExportGroup';box.style.cssText='display:inline-flex;gap:6px;flex-wrap:wrap';box.innerHTML=`<button class="button ghost" id="agExportTxt" type="button">↓ ${d().txt}</button><button class="button ghost" id="agExportMd" type="button">↓ ${d().md}</button><button class="button ghost" id="agExportPdf" type="button">↓ ${d().pdf}</button>`;row.appendChild(box);box.querySelector('#agExportTxt').onclick=()=>download(ui.source.value,'text/plain;charset=utf-8',`antigolem-text-${date()}.txt`);box.querySelector('#agExportMd').onclick=()=>download(ui.source.value,'text/markdown;charset=utf-8',`antigolem-text-${date()}.md`);box.querySelector('#agExportPdf').onclick=pdf;}
  document.addEventListener('DOMContentLoaded',mount,{once:true});if(document.readyState!=='loading')mount();
})();