(() => {
  const LANGS={de:'de',en:'en',fr:'fr',es:'es',it:'it',nl:'nl'};
  const OCR_LANG={de:'deu',en:'eng',fr:'fra',es:'spa',it:'ita',nl:'nld'};
  const LABELS={
    de:{title:'Forensic Workbench',heat:'Inline-Heatmap',diff:'Vorher / Nachher',reply:'Reply Studio',docs:'Document Lab',why:'Warum diese Wertung?',gen:'Verbesserungsvorschlag erzeugen',ai:'Vorschlag lokal verfeinern',acceptAll:'Alle Verbesserungen anwenden',history:'Versionen',restore:'Version wiederherstellen',original:'Original',improved:'Verbessert',accept:'Übernehmen',reject:'Original behalten',before:'Vorher',after:'Nachher',errors:'begründete Auffälligkeiten',bad:'schlecht',amb:'ambivalent',risk:'kritisch/hoch',clarity:'Klarheit',replyGen:'Antwort erzeugen',copy:'Antwort kopieren',tone:'Stil',evidence:'Belegbasis',openFiles:'Dateien hinzufügen',combine:'Alle Texte kombinieren',compare:'Dokumentvergleich',load:'In Editor laden',ocr:'OCR',processing:'Verarbeitung …',noDocs:'Noch keine Dokumente geladen.',docNote:'PDF/DOCX/OCR laden freie Browser-Runtimes beim ersten Einsatz; die eigentliche Extraktion/OCR läuft danach lokal im Gerät/Browser.',score:'Strenge Satzwertung',issues:'Fehlerquote',sentences:'Sätze'},
    en:{title:'Forensic Workbench',heat:'Inline heatmap',diff:'Before / after',reply:'Reply Studio',docs:'Document Lab',why:'Why this rating?',gen:'Generate improvement proposal',ai:'Refine proposal locally',acceptAll:'Apply all improvements',history:'Versions',restore:'Restore version',original:'Original',improved:'Improved',accept:'Accept',reject:'Keep original',before:'Before',after:'After',errors:'grounded findings',bad:'bad',amb:'ambivalent',risk:'critical/high',clarity:'clarity',replyGen:'Generate reply',copy:'Copy reply',tone:'Style',evidence:'Evidence base',openFiles:'Add files',combine:'Combine all texts',compare:'Document comparison',load:'Load into editor',ocr:'OCR',processing:'Processing …',noDocs:'No documents loaded yet.',docNote:'PDF/DOCX/OCR load free browser runtimes on first use; extraction/OCR then runs locally on the device/browser.',score:'Strict sentence score',issues:'Issue rate',sentences:'sentences'},
    fr:{title:'Atelier forensique',heat:'Heatmap en ligne',diff:'Avant / après',reply:'Reply Studio',docs:'Document Lab',why:'Pourquoi cette note ?',gen:'Générer une amélioration',ai:'Affiner localement',acceptAll:'Appliquer toutes les améliorations',history:'Versions',restore:'Restaurer',original:'Original',improved:'Amélioré',accept:'Accepter',reject:'Garder original',before:'Avant',after:'Après',errors:'anomalies justifiées',bad:'mauvais',amb:'ambigu',risk:'critique/élevé',clarity:'clarté',replyGen:'Générer réponse',copy:'Copier réponse',tone:'Style',evidence:'Base factuelle',openFiles:'Ajouter fichiers',combine:'Combiner les textes',compare:'Comparer documents',load:'Charger dans éditeur',ocr:'OCR',processing:'Traitement …',noDocs:'Aucun document chargé.',docNote:'PDF/DOCX/OCR chargent des runtimes libres au premier usage; extraction/OCR s’effectuent ensuite localement.',score:'Score strict',issues:'Taux d’anomalies',sentences:'phrases'},
    es:{title:'Forensic Workbench',heat:'Mapa de calor',diff:'Antes / después',reply:'Reply Studio',docs:'Document Lab',why:'¿Por qué esta valoración?',gen:'Generar mejora',ai:'Refinar localmente',acceptAll:'Aplicar todas las mejoras',history:'Versiones',restore:'Restaurar',original:'Original',improved:'Mejorado',accept:'Aceptar',reject:'Mantener original',before:'Antes',after:'Después',errors:'hallazgos justificados',bad:'malas',amb:'ambiguas',risk:'críticas/altas',clarity:'claridad',replyGen:'Generar respuesta',copy:'Copiar respuesta',tone:'Estilo',evidence:'Base de evidencia',openFiles:'Añadir archivos',combine:'Combinar textos',compare:'Comparar documentos',load:'Cargar en editor',ocr:'OCR',processing:'Procesando …',noDocs:'Aún no hay documentos.',docNote:'PDF/DOCX/OCR cargan runtimes libres la primera vez; después la extracción/OCR se ejecuta localmente.',score:'Puntuación estricta',issues:'Tasa de incidencias',sentences:'frases'},
    it:{title:'Forensic Workbench',heat:'Heatmap inline',diff:'Prima / dopo',reply:'Reply Studio',docs:'Document Lab',why:'Perché questa valutazione?',gen:'Genera miglioramento',ai:'Affina localmente',acceptAll:'Applica tutti i miglioramenti',history:'Versioni',restore:'Ripristina',original:'Originale',improved:'Migliorato',accept:'Accetta',reject:'Mantieni originale',before:'Prima',after:'Dopo',errors:'rilievi motivati',bad:'cattive',amb:'ambivalenti',risk:'critiche/alte',clarity:'chiarezza',replyGen:'Genera risposta',copy:'Copia risposta',tone:'Stile',evidence:'Base probatoria',openFiles:'Aggiungi file',combine:'Combina testi',compare:'Confronta documenti',load:'Carica nell’editor',ocr:'OCR',processing:'Elaborazione …',noDocs:'Nessun documento caricato.',docNote:'PDF/DOCX/OCR caricano runtime liberi al primo uso; poi estrazione/OCR avvengono localmente.',score:'Punteggio rigoroso',issues:'Tasso rilievi',sentences:'frasi'},
    nl:{title:'Forensic Workbench',heat:'Inline heatmap',diff:'Voor / na',reply:'Reply Studio',docs:'Document Lab',why:'Waarom deze beoordeling?',gen:'Verbeteringsvoorstel maken',ai:'Lokaal verfijnen',acceptAll:'Alle verbeteringen toepassen',history:'Versies',restore:'Versie herstellen',original:'Origineel',improved:'Verbeterd',accept:'Overnemen',reject:'Origineel houden',before:'Voor',after:'Na',errors:'onderbouwde bevindingen',bad:'slecht',amb:'ambivalent',risk:'kritiek/hoog',clarity:'helderheid',replyGen:'Antwoord maken',copy:'Antwoord kopiëren',tone:'Stijl',evidence:'Onderbouwing',openFiles:'Bestanden toevoegen',combine:'Teksten combineren',compare:'Documenten vergelijken',load:'In editor laden',ocr:'OCR',processing:'Verwerken …',noDocs:'Nog geen documenten geladen.',docNote:'PDF/DOCX/OCR laden bij eerste gebruik vrije browser-runtimes; extractie/OCR draait daarna lokaal.',score:'Strenge zinscore',issues:'Probleempercentage',sentences:'zinnen'}
  };
  const TONES={
    de:[['friendly','Freundlich'],['very-polite','Sehr höflich'],['professional','Professionell'],['short','Kurz / Social'],['detailed','Detailliert konstruktiv'],['question','Als Frage'],['unfriendly','Unfreundlich'],['diss','Dissend'],['challenge','Herausfordernd']],
    en:[['friendly','Friendly'],['very-polite','Very polite'],['professional','Professional'],['short','Short / social'],['detailed','Detailed constructive'],['question','Question-led'],['unfriendly','Unfriendly'],['diss','Dissing'],['challenge','Challenging']],
    fr:[['friendly','Amical'],['very-polite','Très poli'],['professional','Professionnel'],['short','Court / social'],['detailed','Constructif détaillé'],['question','Sous forme de question'],['unfriendly','Peu aimable'],['diss','Piquant'],['challenge','Provocateur']],
    es:[['friendly','Amable'],['very-polite','Muy educado'],['professional','Profesional'],['short','Corto / social'],['detailed','Constructivo detallado'],['question','En forma de pregunta'],['unfriendly','Poco amable'],['diss','Dissing'],['challenge','Desafiante']],
    it:[['friendly','Gentile'],['very-polite','Molto cortese'],['professional','Professionale'],['short','Breve / social'],['detailed','Costruttivo dettagliato'],['question','Come domanda'],['unfriendly','Scortese'],['diss','Pungente'],['challenge','Sfidante']],
    nl:[['friendly','Vriendelijk'],['very-polite','Zeer beleefd'],['professional','Professioneel'],['short','Kort / social'],['detailed','Uitgebreid constructief'],['question','Als vraag'],['unfriendly','Onvriendelijk'],['diss','Dissend'],['challenge','Uitdagend']]
  };

  const state={docs:[],proposal:[],original:[],history:[],tab:'heat'};
  const d=()=>LABELS[ui.lang.value]||LABELS.en;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));

  function analyzeText(text){
    const s=splitSentences(text||'');
    const r=s.map((x,i)=>classifySentence(x,ui.lang.value,i));
    const bad=r.filter(x=>x.rating==='SCHLECHT').length,amb=r.filter(x=>x.rating==='AMBIVALENT').length,good=r.filter(x=>x.rating==='GUT').length;
    const risk=r.filter(x=>x.risk==='KRITISCH'||x.risk==='HOCH').length,d2=r.filter(x=>x.d==='D-2+').length,d1=r.filter(x=>x.d==='D-1').length;
    const neg=r.reduce((n,x)=>n+x.neg,0),abs=r.reduce((n,x)=>n+(x.absolutism||0),0),modal=r.reduce((n,x)=>n+(x.modalPressure||0),0),diff=r.reduce((n,x)=>n+x.diff+x.over,0);
    const issue=bad+amb,total=Math.max(1,r.length);
    const constructive=Math.round(good/total*100);
    const clarity=clamp(Math.round(100-(bad/total*38)-(amb/total*18)-(d2/total*28)-(d1/total*8)+constructive*.12),0,100);
    return {sentences:s,results:r,total:r.length,bad,amb,good,risk,d1,d2,neg,abs,modal,diff,issue,errorPct:Math.round(issue/total*100),badPct:Math.round(bad/total*100),riskPct:Math.round(risk/total*100),clarity};
  }

  function scoreBreakdown(r){
    const parts=[];let score=0;
    const add=(label,val)=>{if(!val)return;parts.push({label,val});score+=val};
    add('Negative normalization',r.neg*3);
    add('D-2+ ghost-context',r.d==='D-2+'?4:0);
    add('D-1 reference distance',r.d==='D-1'?2:0);
    add('Absolutism',(r.absolutism||0)*1);
    add('Modal pressure',(r.modalPressure||0)*1);
    add('Responsibility diffusion',(r.diff+r.over)*1);
    add('Constructive framing',r.pos?Math.max(-2,-r.pos):0);
    return {score:Math.max(0,score),parts};
  }

  function mount(){
    if(document.getElementById('agWorkbench'))return;
    const section=document.createElement('section');section.id='agWorkbench';section.className='panel';section.style.cssText='margin-top:18px;padding:16px;overflow:hidden';
    section.innerHTML=`<div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><div><span class="step">04</span><h2 id="agWorkbenchTitle" style="display:inline;margin-left:8px"></h2></div><div id="agWorkbenchTabs" style="display:flex;gap:7px;flex-wrap:wrap"></div></div><div id="agWorkbenchBody" style="margin-top:14px"></div>`;
    const methodology=document.querySelector('.methodology');(methodology?.parentNode||document.querySelector('main')).insertBefore(section,methodology||null);
    renderTabs();render();
    ui.source.addEventListener('input',()=>{if(state.tab==='heat')renderHeat();});
    ui.analyze.addEventListener('click',()=>setTimeout(()=>{renderHeat();renderReplyEvidence();},0));
    ui.lang.addEventListener('change',()=>setTimeout(()=>{renderTabs();render();},0));
  }

  function renderTabs(){
    const l=d();document.getElementById('agWorkbenchTitle').textContent=l.title;
    const tabs=[['heat',l.heat],['diff',l.diff],['reply',l.reply],['docs',l.docs]];
    document.getElementById('agWorkbenchTabs').innerHTML=tabs.map(([id,label])=>`<button class="button ${state.tab===id?'primary':'ghost'}" data-agtab="${id}" type="button" style="padding:8px 12px">${esc(label)}</button>`).join('');
    document.querySelectorAll('[data-agtab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.agtab;renderTabs();render();});
  }
  function render(){if(state.tab==='heat')renderHeat();else if(state.tab==='diff')renderDiff();else if(state.tab==='reply')renderReply();else renderDocs();}

  function renderHeat(){
    const body=document.getElementById('agWorkbenchBody');if(!body)return;const a=analyzeText(ui.source.value);const l=d();
    if(!a.total){body.innerHTML='<p class="micro">Analyze or paste text to build the forensic heatmap.</p>';return;}
    body.innerHTML=`<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:8px;margin-bottom:12px"><div class="metric bad"><span>${l.errors}</span><b>${a.issue} · ${a.errorPct}%</b></div><div class="metric"><span>${l.risk}</span><b>${a.risk} · ${a.riskPct}%</b></div><div class="metric"><span>${l.clarity}</span><b>${a.clarity}/100</b></div><div class="metric"><span>${l.sentences}</span><b>${a.total}</b></div></div><div id="agHeatmap" style="line-height:2.15;background:#07111f;border:1px solid #223b60;border-radius:16px;padding:14px;max-height:360px;overflow:auto">${a.results.map((r,i)=>{const bg=r.rating==='SCHLECHT'?'rgba(255,82,96,.18)':r.rating==='AMBIVALENT'?'rgba(255,174,66,.17)':r.rating==='GUT'?'rgba(55,210,145,.14)':'rgba(132,158,190,.08)';const border=r.rating==='SCHLECHT'?'#ff6573':r.rating==='AMBIVALENT'?'#f4b85a':r.rating==='GUT'?'#42dca0':'#38506e';return `<button data-sent="${i}" title="${r.rating} / ${r.risk}" style="display:inline;text-align:left;color:#e8f1ff;background:${bg};border:1px solid ${border};border-radius:8px;padding:3px 6px;margin:2px;cursor:pointer;font:inherit">${esc(r.sentence)}</button>`}).join(' ')}</div><div id="agSentenceExplain" style="margin-top:10px"></div>`;
    body.querySelectorAll('[data-sent]').forEach(btn=>btn.onclick=()=>explainSentence(a.results[Number(btn.dataset.sent)]));
  }
  function explainSentence(r){
    const b=scoreBreakdown(r),el=document.getElementById('agSentenceExplain');if(!el)return;const l=d();
    el.innerHTML=`<div style="border:1px solid #31537d;border-radius:14px;padding:13px;background:#091827"><b>${l.why}</b><div style="display:flex;gap:8px;flex-wrap:wrap;margin:8px 0"><span class="pill active">${r.rating}</span><span class="pill">${r.risk}</span><span class="pill">${r.d}</span><span class="pill">${l.score}: ${b.score}</span></div><div>${b.parts.length?b.parts.map(p=>`<div style="display:flex;justify-content:space-between;border-top:1px solid #1f3654;padding:5px 0"><span>${esc(p.label)}</span><b>${p.val>0?'+':''}${p.val}</b></div>`).join(''):'<span class="micro">No strict penalty signals detected.</span>'}</div></div>`;
  }

  const SAFE_REWRITE={
    de:[[/(\b)niemals\b/giu,'$1selten'],[/(\b)nie\b/giu,'$1selten'],[/(\b)immer\b/giu,'$1häufig'],[/\bman\b/giu,'die jeweils verantwortliche Person'],[/\bunmöglich\b/giu,'unter den aktuellen Bedingungen schwer umsetzbar'],[/\bmachtlos\b/giu,'mit begrenztem Handlungsspielraum'],[/\bProbleme?\b/giu,'Herausforderung'],[/\bscheitern\b/giu,'das angestrebte Ergebnis verfehlen']],
    en:[[/\bnever\b/giu,'rarely'],[/\balways\b/giu,'often'],[/\bimpossible\b/giu,'difficult under the current conditions'],[/\bpowerless\b/giu,'with limited room to act'],[/\bproblems?\b/giu,'challenge'],[/\bfail(?:s|ed|ing)?\b/giu,'does not achieve the intended result']],
    fr:[[/\bjamais\b/giu,'rarement'],[/\btoujours\b/giu,'souvent'],[/\bimpossible\b/giu,'difficile dans les conditions actuelles'],[/\bproblèmes?\b/giu,'défi']],
    es:[[/\bnunca\b/giu,'rara vez'],[/\bsiempre\b/giu,'a menudo'],[/\bimposible\b/giu,'difícil en las condiciones actuales'],[/\bproblemas?\b/giu,'reto']],
    it:[[/\bmai\b/giu,'raramente'],[/\bsempre\b/giu,'spesso'],[/\bimpossibile\b/giu,'difficile nelle condizioni attuali'],[/\bproblemi?\b/giu,'sfida']],
    nl:[[/\bnooit\b/giu,'zelden'],[/\baltijd\b/giu,'vaak'],[/\bonmogelijk\b/giu,'moeilijk onder de huidige omstandigheden'],[/\bproblemen?\b/giu,'uitdaging']]
  };
  function improveSentence(s){let out=s;for(const [re,to] of (SAFE_REWRITE[ui.lang.value]||SAFE_REWRITE.en))out=out.replace(re,to);return out;}
  function makeProposal(){state.original=splitSentences(ui.source.value);state.proposal=state.original.map(improveSentence);renderDiff();}
  function pushVersion(text,label){if(!text.trim())return;state.history.unshift({text,label:label||new Date().toLocaleTimeString(),at:Date.now()});state.history=state.history.slice(0,12);}
  function applyText(text){pushVersion(ui.source.value,'Before change');ui.source.value=text;ui.source.dispatchEvent(new Event('input',{bubbles:true}));run();}

  function renderDiff(){
    const body=document.getElementById('agWorkbenchBody'),l=d();if(!body)return;if(!state.proposal.length&&ui.source.value.trim())makeProposal();
    const before=analyzeText((state.original.length?state.original:splitSentences(ui.source.value)).join(' ')),after=analyzeText(state.proposal.join(' '));
    body.innerHTML=`<div class="toolRow"><button id="agGenProposal" class="button primary" type="button">${l.gen}</button><button id="agAiProposal" class="button ghost" type="button">AI · ${l.ai}</button><button id="agAcceptAll" class="button ghost" type="button">✓ ${l.acceptAll}</button></div><div id="agDiffStatus" class="micro" style="margin:8px 0"></div>${state.proposal.length?`<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px;margin:10px 0"><div class="metric bad"><span>${l.before}</span><b>${before.issue} · ${before.errorPct}%</b><small>${l.clarity}: ${before.clarity}</small></div><div class="metric good"><span>${l.after}</span><b>${after.issue} · ${after.errorPct}%</b><small>${l.clarity}: ${after.clarity}</small></div></div><div style="max-height:520px;overflow:auto">${state.proposal.map((p,i)=>{const o=state.original[i]||'';return `<div style="border:1px solid #294564;border-radius:14px;padding:10px;margin:8px 0;background:#081522"><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><div><small style="color:#90a7c7">${l.original}</small><div>${esc(o)}</div></div><div><small style="color:#65dfb6">${l.improved}</small><div>${esc(p)}</div></div></div><div style="display:flex;gap:7px;margin-top:8px"><button class="button ghost" data-accept="${i}" type="button">✓ ${l.accept}</button><button class="button ghost" data-reject="${i}" type="button">↶ ${l.reject}</button></div></div>`}).join('')}</div>`:'<p class="micro">No proposal yet.</p>'}<details style="margin-top:12px"><summary>${l.history} (${state.history.length})</summary><div>${state.history.map((v,i)=>`<button class="button ghost" data-version="${i}" type="button" style="margin:4px">${new Date(v.at).toLocaleTimeString()} · ${l.restore}</button>`).join('')||'<span class="micro">—</span>'}</div></details>`;
    body.querySelector('#agGenProposal').onclick=()=>{state.original=splitSentences(ui.source.value);state.proposal=state.original.map(improveSentence);renderDiff();};
    body.querySelector('#agAcceptAll').onclick=()=>{if(state.proposal.length)applyText(state.proposal.join(' '));};
    body.querySelector('#agAiProposal').onclick=refineProposalAI;
    body.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>{const i=+b.dataset.accept;state.original[i]=state.proposal[i];applyText(state.original.join(' '));state.original=splitSentences(ui.source.value);state.proposal=state.original.map(improveSentence);renderDiff();});
    body.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>{const i=+b.dataset.reject;state.proposal[i]=state.original[i];renderDiff();});
    body.querySelectorAll('[data-version]').forEach(b=>b.onclick=()=>{const v=state.history[+b.dataset.version];if(v)applyText(v.text);});
  }
  async function refineProposalAI(){
    const st=document.getElementById('agDiffStatus');if(!window.AntiGolemLocalAI?.ask){st.textContent='Local AI unavailable; deterministic proposal remains active.';return;}
    const source=ui.source.value.trim();if(!source)return;st.textContent=d().processing;
    try{const prompt=`Rewrite the following text in ${ui.lang.value}. Preserve every factual claim, name, number, link, chronology and viewpoint. Reduce ambiguous pronouns, unnecessary absolutism, diffuse responsibility, coercive modal pressure and failure/powerlessness-as-default framing. Keep necessary warnings but attach them to conditions, agency or next steps. Output only the revised text.\n\n${source}`;const out=await window.AntiGolemLocalAI.ask(prompt,s=>st.textContent=s);if(out){const s=String(out).replace(/^```(?:text|markdown)?/i,'').replace(/```$/,'').trim(),old=splitSentences(source),neu=splitSentences(s);state.original=old;state.proposal=neu.length===old.length?neu:old.map(improveSentence);if(neu.length!==old.length)st.textContent='AI rewrite had a different sentence count; sentence-level diff uses the safe deterministic proposal.';renderDiff();}}catch(e){st.textContent=String(e?.message||e);}
  }

  function evidence(a){return `${a.issue}/${a.total} (${a.errorPct}%) · BAD ${a.bad}/${a.total} (${a.badPct}%) · AMB ${a.amb}/${a.total} (${Math.round(a.amb/Math.max(1,a.total)*100)}%) · CRITICAL/HIGH ${a.risk}/${a.total} (${a.riskPct}%) · D-1 ${a.d1} · D-2+ ${a.d2} · negative ${a.neg} · absolutism ${a.abs} · modal ${a.modal} · responsibility ${a.diff}`;}
  function toneReply(tone,a){
    const L=ui.lang.value,pct=a.errorPct,bad=a.bad,amb=a.amb,total=a.total;
    const stats=L==='de'?`${a.issue} von ${total} Sätzen (${pct} %) wurden begründet als problematisch oder ambivalent markiert; davon ${bad} SCHLECHT und ${amb} AMBIVALENT.`:`${a.issue} of ${total} sentences (${pct}%) were groundedly flagged as problematic or ambivalent; ${bad} BAD and ${amb} AMBIVALENT.`;
    const de={friendly:`Danke für den Beitrag. Inhaltlich kann ich den Punkt nachvollziehen. Beim Wording sehe ich aber Verbesserungspotenzial: ${stats} Könntest du einige absolute oder negative Default-Formulierungen präziser, eindeutiger und lösungsorientierter formulieren? Das würde die Aussage stärker machen, ohne den Inhalt abzuschwächen.`,
      'very-polite':`Vielen Dank fürs Teilen. Darf ich eine kleine Bitte zum Wording ergänzen? ${stats} Vielleicht könntest du besonders harte Verallgemeinerungen, unklare Bezüge und pauschale Verantwortungszuschreibungen etwas präzisieren. Ich glaube, der eigentliche Punkt käme dadurch noch klarer und konstruktiver rüber.`,
      professional:`Sachlicher Wording-Hinweis: ${stats} Auffällig sind insbesondere ${a.neg} negative Normalisierungssignale, ${a.abs} Absolutismen, ${a.modal} Modal-Druck-Signale und ${a.d1+a.d2} Referenzdistanz-Fälle. Empfehlung: Subjekte expliziter benennen, Bedingungen ergänzen, absolute Aussagen begrenzen und Probleme direkt mit Handlungsoptionen koppeln.`,
      short:`Wording-Hinweis: ${pct}% der Sätze wurden als problematisch/ambivalent markiert (${bad} schlecht, ${amb} ambivalent). Weniger Absolutismen + klarere Bezüge + mehr konkrete Handlungsoptionen würden den Post deutlich stärker machen.`,
      detailed:`Ich würde den Inhalt nicht pauschal zurückweisen, aber das Wording deutlich überarbeiten. ${stats} Zusätzlich wurden ${a.risk} kritische/hohe Risikostellen (${a.riskPct}%), ${a.d1} D-1- und ${a.d2} D-2+-Bezüge erkannt. Besonders sinnvoll wären: klare Subjekte statt diffuser Verantwortlichkeit, weniger absolute Aussagen, Warnungen mit konkreten Bedingungen und nächste Schritte statt Scheitern/Ohnmacht als Default.`,
      question:`Wenn der inhaltliche Punkt tragfähig ist: Könnte man ihn nicht präziser formulieren? ${stats} Wäre es möglich, die absoluten Aussagen einzugrenzen, unklare Pronomen eindeutig zu binden und negative Erwartungen direkt mit Bedingungen oder Lösungswegen zu verknüpfen?`,
      unfriendly:`So ist das Wording unnötig schwach. ${stats} ${pct}% problematische/ambivalente Sätze sind zu viel, wenn der Text überzeugend wirken soll. Weniger Pauschalisierung, klarere Verantwortlichkeiten und konkrete Lösungswege würden dem Argument deutlich helfen.`,
      diss:`Ganz schön viel sprachliche Gewissheit für einen Text, bei dem ${pct}% der Sätze als problematisch oder ambivalent auffallen (${bad} schlecht, ${amb} ambivalent). Wenn die Aussage wirklich stark ist, sollte sie auch ohne Absolutismen, diffuse Verantwortlichkeit und negative Default-Rahmung funktionieren.`,
      challenge:`Challenge: Formuliere denselben Punkt noch einmal, aber ohne pauschale Absolutismen, ohne unklare Verantwortlichkeit und ohne Scheitern/Ohnmacht als Default. Aktuell liegen ${a.issue}/${total} Sätze (${pct}%) im problematischen oder ambivalenten Bereich. Wenn das Argument trägt, müsste es danach sogar klarer und stärker werden.`};
    const en={friendly:`Thanks for the post. I can follow the substantive point, but the wording could be stronger: ${stats} Could you make some absolute or negative-default formulations more precise, explicit and solution-oriented?`,professional:`Wording audit: ${stats} The text also contains ${a.neg} negative-normalization cues, ${a.abs} absolutism cues, ${a.modal} modal-pressure cues and ${a.d1+a.d2} reference-distance cases.`,short:`Wording note: ${pct}% of sentences were flagged as problematic/ambivalent (${bad} bad, ${amb} ambivalent). Clearer references and fewer absolutes would make the post stronger.`,detailed:`I would not dismiss the underlying point, but I would revise the wording substantially. ${stats} ${a.risk} sentences are critical/high (${a.riskPct}%). Make subjects explicit, limit absolute claims and connect warnings to conditions and actionable next steps.`,question:`If the underlying point is solid, could it be phrased more precisely? ${stats} Could the absolute claims be narrowed, pronouns bound more clearly, and negative expectations connected to concrete conditions or solutions?`,unfriendly:`The wording is unnecessarily weak. ${stats} A ${pct}% problem/ambiguity rate is too high for a text that wants to persuade.`,diss:`That is a lot of certainty for a text where ${pct}% of the sentences are flagged as problematic or ambivalent (${bad} bad, ${amb} ambivalent). If the argument is strong, it should survive without vague responsibility and absolute framing.`,challenge:`Challenge: make the same point again without blanket absolutes, vague responsibility or failure-as-default framing. Right now ${a.issue}/${total} sentences (${pct}%) fall into the problematic/ambivalent range.`, 'very-polite':`Thank you for sharing this. May I suggest a wording refinement? ${stats} More explicit references and slightly less absolute framing could make the underlying point even clearer.`};
    if(L==='de')return de[tone]||de.friendly;if(L==='en')return en[tone]||en.friendly;
    const prefix={fr:'Retour sur la formulation',es:'Comentario sobre la redacción',it:'Nota sul wording',nl:'Wording-opmerking'}[L]||'Wording note';
    const edge={unfriendly:'Direct',diss:'Sharp',challenge:'Challenge'}[tone]||'';
    return `${prefix}${edge?' · '+edge:''}: ${evidence(a)}. ${tone==='question'?'Could the wording be made more precise, less absolute, and clearer about responsibility and next steps?':'Please consider clearer references, less unnecessary absolutism, and more explicit solution or action framing.'}`;
  }
  function renderReply(){
    const body=document.getElementById('agWorkbenchBody'),l=d(),a=analyzeText(ui.source.value);if(!body)return;const tones=TONES[ui.lang.value]||TONES.en;
    body.innerHTML=`<div style="display:flex;gap:10px;align-items:end;flex-wrap:wrap"><label class="selectWrap"><span>${l.tone}</span><select id="agTone">${tones.map(([v,n])=>`<option value="${v}">${esc(n)}</option>`).join('')}</select></label><button id="agReplyGen" class="button primary" type="button">${l.replyGen}</button><button id="agReplyCopy" class="button ghost" type="button">${l.copy}</button></div><div id="agReplyEvidence" class="micro" style="margin:10px 0"></div><textarea id="agReplyText" style="width:100%;min-height:180px;background:#07111f;color:#edf6ff;border:1px solid #294766;border-radius:14px;padding:12px;font:inherit"></textarea>`;
    const update=()=>{const cur=analyzeText(ui.source.value);document.getElementById('agReplyEvidence').textContent=`${l.evidence}: ${evidence(cur)}`;document.getElementById('agReplyText').value=toneReply(document.getElementById('agTone').value,cur);};
    body.querySelector('#agReplyGen').onclick=update;body.querySelector('#agTone').onchange=update;body.querySelector('#agReplyCopy').onclick=async()=>{await navigator.clipboard.writeText(body.querySelector('#agReplyText').value);};update();
  }
  function renderReplyEvidence(){if(state.tab==='reply')renderReply();}

  async function ensureMammoth(){if(globalThis.mammoth)return globalThis.mammoth;await loadScript('https://cdn.jsdelivr.net/npm/mammoth@1.8.0/mammoth.browser.min.js');return globalThis.mammoth;}
  async function ensureTesseract(){if(globalThis.Tesseract)return globalThis.Tesseract;await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js');return globalThis.Tesseract;}
  function loadScript(src){return new Promise((res,rej)=>{const old=[...document.scripts].find(s=>s.src===src);if(old){if(old.dataset.loaded)return res();old.addEventListener('load',res,{once:true});return;}const s=document.createElement('script');s.src=src;s.crossOrigin='anonymous';s.onload=()=>{s.dataset.loaded='1';res()};s.onerror=rej;document.head.appendChild(s);});}
  async function parsePdf(file){const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let out='';for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),c=await page.getTextContent();out+=`\n\n[Page ${i}]\n`+c.items.map(x=>x.str).join(' ');}return out.trim();}
  function rtfToText(s){return s.replace(/\\par[d]?/g,'\n').replace(/\\'[0-9a-fA-F]{2}/g,'').replace(/\\[a-zA-Z]+-?\d* ?/g,'').replace(/[{}]/g,'').replace(/\n{3,}/g,'\n\n').trim();}
  async function parseFile(file,status){
    const name=file.name.toLowerCase();
    if(file.type.startsWith('image/')){status(`${d().ocr}: ${file.name}`);const t=await ensureTesseract();const r=await t.recognize(file,OCR_LANG[ui.lang.value]||'eng',{logger:m=>{if(m.progress)status(`${d().ocr}: ${Math.round(m.progress*100)}%`)}});return r.data?.text||'';}
    if(name.endsWith('.pdf')){status(`PDF: ${file.name}`);return parsePdf(file);}
    if(name.endsWith('.docx')){status(`DOCX: ${file.name}`);const m=await ensureMammoth(),r=await m.extractRawText({arrayBuffer:await file.arrayBuffer()});return r.value||'';}
    let text=await file.text();if(name.endsWith('.html')||name.endsWith('.htm')){const doc=new DOMParser().parseFromString(text,'text/html');text=doc.body?.innerText||text;}if(name.endsWith('.rtf'))text=rtfToText(text);return text;
  }
  async function ingestFiles(files){
    const status=document.getElementById('agDocStatus');for(const file of files){try{status.textContent=`${d().processing} ${file.name}`;const text=await parseFile(file,s=>status.textContent=s);const a=analyzeText(text);state.docs.push({name:file.name,text,a});renderDocs();}catch(e){status.textContent=`${file.name}: ${e?.message||e}`;}}if(document.getElementById('agDocStatus'))document.getElementById('agDocStatus').textContent='';
  }
  function renderDocs(){
    const body=document.getElementById('agWorkbenchBody'),l=d();if(!body)return;
    body.innerHTML=`<div class="toolRow"><label class="button primary fileButton"><input id="agDocInput" type="file" multiple accept=".txt,.md,.html,.htm,.csv,.json,.xml,.rtf,.pdf,.docx,image/*"/><span>${l.openFiles}</span></label><button id="agCombineDocs" class="button ghost" type="button">${l.combine}</button></div><div id="agDocStatus" class="micro" style="margin:8px 0"></div><p class="micro">${l.docNote}</p>${state.docs.length?`<div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th style="text-align:left">Document</th><th>${l.sentences}</th><th>${l.issues}</th><th>${l.clarity}</th><th></th></tr></thead><tbody>${state.docs.map((x,i)=>`<tr style="border-top:1px solid #223a59"><td style="padding:9px">${esc(x.name)}</td><td style="text-align:center">${x.a.total}</td><td style="text-align:center">${x.a.issue} · ${x.a.errorPct}%</td><td style="text-align:center">${x.a.clarity}</td><td style="padding:6px"><button class="button ghost" data-load-doc="${i}" type="button">${l.load}</button></td></tr>`).join('')}</tbody></table></div>`:`<p>${l.noDocs}</p>`}`;
    body.querySelector('#agDocInput').onchange=e=>ingestFiles([...e.target.files]);body.querySelector('#agCombineDocs').onclick=()=>{if(!state.docs.length)return;applyText(state.docs.map(x=>`### ${x.name}\n${x.text}`).join('\n\n'));};body.querySelectorAll('[data-load-doc]').forEach(b=>b.onclick=()=>{const x=state.docs[+b.dataset.loadDoc];if(x)applyText(x.text);});
  }

  document.addEventListener('DOMContentLoaded',mount,{once:true});if(document.readyState!=='loading')mount();
  window.AntiGolemWorkbench={open(tab){state.tab=tab||'heat';renderTabs();render();document.getElementById('agWorkbench')?.scrollIntoView({behavior:'smooth',block:'start'});},stats(){return analyzeText(ui.source.value)},generateReply(tone){return toneReply(tone||'friendly',analyzeText(ui.source.value))}};
})();